# -*- coding: utf-8 -*-
"""Dados_Tratados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q3LFbkMcG7TgWDb--tsxka9gN_fX_NIf
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv('dados_nao_tratados.csv')


#Modificações
#Idade
df["idade"] = pd.to_numeric(df["idade"], errors="coerce")
df["idade"] = df["idade"].fillna(0).astype(int)

#data_inscricão
df['data_inscricao'] = pd.to_datetime(df["data_inscricao"], errors="coerce")

#nota
# Converte para numérico (qualquer coisa inválida vira NaN)
df["nota"] = pd.to_numeric(df["nota"], errors="coerce")

# Substitui os NaN por 0.0
df["nota"] = df["nota"].fillna(0.0)


df["ativo"] = df["ativo"].str.strip().str.lower()  # remove espaços e deixa minúsculo
df["ativo"] = df["ativo"].map({"sim": True, "não": False, "nao": False, "true": True, "false": False})

#Criar uma  nova coluna
df['Passou'] = df["nota"].apply(lambda x: "Sim" if x >= 7 else "Não")


df.head()