# -*- coding: utf-8 -*-
"""Desafio_Temperatura

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJziCMkjKn6ZKuNnK_o9mcY_g_PhvYfY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#Dados do dia da semana
dias = ['Segunda','Terça', 'Quarta','Quinta','Sexta','Sábado','Domingo']
#7 valores entre 20 a 35 graus
temperaturas = np.random.uniform(20,35,7)
#Criação do data frame
df = pd.DataFrame({
    "Dias":dias,
    "Temperatura(°C)":temperaturas
})

#Calculo da média
media = df["Temperatura(°C)"].mean()
print("media da semana",round(media,2),"°C")

#Gráfico
plt.plot(df["Dias"],df["Temperatura(°C)"],marker = 'o', linestyle= '-',color ='b')
plt.axhline(media,color="r",linestyle ='--',label= f'Média: {round(media,2)} °C' )
plt.title('Variação de temperatura na semana')
plt.xlabel('Dia da semana')
plt.ylabel('Temperatura(°C)')
plt.legend()
plt.grid(True)
plt.show()